const UserRouter = require('./UserRouter')
const ProductRouter = require('./ProductRouter')
const ProvinceRouter = require('./ProvinceRouter')
const DistrictRouter = require('./DistrictRouter')
const CommuneRouter = require('./CommuneRouter')
const LanguageRouter = require('./OptionRouter/LanguageRouter')
const UnitRouter = require('./OptionRouter/UnitRouter')
const FormatRouter = require('./OptionRouter/FormatRouter')
const PublisherRouter = require('./OptionRouter/PublisherRouter')
const ListAddressRouter = require('./ListAddressRouter')
const PromotionRouter = require('./PromotionRouter')
const ShopProfileRouter = require('./ShopProfileRouter')
const SupplierRouter = require('./OptionRouter/SupplierRouter')
const ActiveRouter = require('./OptionRouter/ActiveRouter')
const CategoryRouter = require('./CategoryRouter')
const OrderRouter = require('./OrderRouter')
const OrderActiveListRouter = require('./OrderActiveListRouter')
const FeedbackRouter = require('./FeedbackRouter')
const FavoriteProductRouter = require('./FavoriteProductRouter')
const StaticPageRouter = require('./StaticPageRouter')
const ImportRouter = require('./ImportRouter')
const recommendationRoutes = require('./RecommendationRouter');
const LiveChatMessageRouter = require('./LiveChatMessageRouter')

const routes = (app) => {
    app.use('/api/user', UserRouter)
    app.use('/api/product', ProductRouter)
    app.use('/api/district', DistrictRouter)
    app.use('/api/province', ProvinceRouter)
    app.use('/api/commune', CommuneRouter)
    app.use('/api/language', LanguageRouter)
    app.use('/api/unit', UnitRouter)
    app.use('/api/format', FormatRouter)
    app.use('/api/publisher', PublisherRouter)
    app.use('/api/listAddress', ListAddressRouter)
    app.use('/api/promotion', PromotionRouter)
    app.use('/api/shop-profile', ShopProfileRouter)
    app.use('/api/supplier', SupplierRouter)
    app.use('/api/active', ActiveRouter)
    app.use('/api/category', CategoryRouter)
    app.use('/api/order', OrderRouter)
    app.use('/api/order-active', OrderActiveListRouter)
    app.use('/api/feedback', FeedbackRouter)
    app.use('/api/favorite-product', FavoriteProductRouter)
    app.use('/api/static-page', StaticPageRouter)
    app.use('/api/imports', ImportRouter)
    app.use('/api/recommendation', recommendationRoutes);
    app.use('/api/chat', LiveChatMessageRouter)
}

module.exports = routes;